### ISSUE TITLE
make firewall rule label shorter 

### ISSUE THREAD

**Issue by scardozos** [scardozos/temp_allowlist_linode_fw#1]
Make fw rule label shorter to fix:

 `linode_api4.errors.ApiError: 400: [rules.inbound[0].label] Length must be 3-32 characters;`

https://github.com/scardozos/temp_allowlist_linode_fw/blob/main/app.py#L36-L46

**Comment by zafirazz** [comment]
Hey! I would like to solve this issue. The easy way to solve this would be to rename `temp_allowlist` to `tmpAllowList`

Please let me know if that works or would like me to reformat it another way.

**Comment by scardozos** [comment]
Sounds good! :)

**Comment by scardozos** [comment]
fixed by #2
